In [16]:
import sys
sys.path.append("/home/sara/lib")

In [17]:
import pandas as pd
import os
import numpy as np
import libopf_py
import pandas as pd
import time
import random

from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

from sklearn.svm import SVC
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
#from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.model_selection import cross_validate

from sklearn.model_selection import cross_val_predict
from sklearn import metrics
from sklearn.model_selection import cross_val_score

In [18]:
#def kfoldcv(indices, k = 10, seed = 42):
#    subset = 0
    
#    size = len(indices)
#    subset_size = round(size / k)
#    random.Random(seed).shuffle(indices) 
    
#    subsets = [indices[x:x+subset_size] for x in range(0, len(indices), subset_size)]    
    
#    kfolds = []
#    for i in range(k):
#        test = subsets[i]
 #       train = []
#        for subset in subsets:
#            if subset != test.all():
#                train.append(subset)
#        kfolds.append((train,test))
       
#    return kfolds

#k = kfoldcv(labels_num)
#print(k)

In [20]:
def names_emotions(labels_num):
    i = 0
    labels = []
    while (i < 1924):
        if labels_num[i] == 0.0:
            labels.append("neutro") 
        if labels_num[i] == 2.0:
            labels.append("alegria")
        if labels_num[i] == 9.0:
            labels.append("surpresa")
        if labels_num[i] == 12.0:
            labels.append("tristeza")
        if labels_num[i] == 13.0:
            labels.append("medo")
        if labels_num[i] == 21.0:
            labels.append("nojo")
        if labels_num[i] == 22.0:
            labels.append("raiva")
        i += 1
    return labels

In [21]:
df = pd.read_csv("csv_dataset/dataframe_7emocoes com numeros.csv", header=None, sep=';')
df = df.drop([0], axis=0)
df = df.drop(columns=[0])

print(df)

        1      2      3      4      5      6      7      8      9      10   \
1      93.0  212.0   96.0  262.0  104.0  310.0  110.0  358.0  121.0  406.0   
2      92.0  215.0   96.0  265.0  105.0  314.0  111.0  362.0  122.0  409.0   
3      95.0  218.0   99.0  268.0  106.0  318.0  112.0  366.0  123.0  412.0   
4      92.0  224.0   94.0  276.0  102.0  327.0  109.0  376.0  121.0  423.0   
5      85.0  214.0   87.0  267.0   95.0  319.0  103.0  370.0  116.0  419.0   
6      87.0  219.0   91.0  272.0   99.0  323.0  108.0  374.0  120.0  424.0   
7      85.0  216.0   89.0  267.0   97.0  317.0  105.0  367.0  116.0  416.0   
8      87.0  214.0   90.0  266.0   98.0  316.0  107.0  365.0  119.0  412.0   
9      93.0  218.0   96.0  269.0  104.0  319.0  109.0  367.0  120.0  415.0   
10     88.0  215.0   92.0  265.0   99.0  314.0  105.0  362.0  115.0  410.0   
11     88.0  208.0   92.0  259.0   99.0  309.0  104.0  358.0  115.0  406.0   
12     95.0  218.0   98.0  271.0  105.0  323.0  111.0  373.0  12

In [22]:
features = df.iloc[0:1925,0:136]
features = features.to_numpy()
features = features.astype('float64')

print(features)
print(len(features))

[[ 93. 212.  96. ... 408. 251. 405.]
 [ 92. 215.  96. ... 411. 251. 408.]
 [ 95. 218.  99. ... 413. 253. 410.]
 ...
 [ 75. 213.  79. ... 404. 238. 402.]
 [ 83. 211.  87. ... 407. 244. 405.]
 [ 71. 202.  75. ... 396. 233. 394.]]
1924


In [23]:
labels = df.iloc[0:,136]
labels = labels.to_numpy()
labels = labels.astype('float64')
print(labels)
print(len(labels))

[ 0.  0.  0. ... 22. 22. 22.]
1924


In [10]:
#labels = names_emotions(labels)
#print(labels)

['neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro', 'neutro',

In [24]:
n_samples = len(features)
print(n_samples)

1924


In [25]:
# adaptações ao OPF.
def opf():
        
    # OPF only supports 32 bits labels at the moment
    label_train_32 = train_labels.astype(np.int32)
    label_test_32 = test_labels.astype(np.int32)

    O = libopf_py.OPF()

    O.fit(train_feat, label_train_32)

    predicted = O.predict(test_feat)
    name = "OPF"
    acc = accuracy_score(label_test_32, predicted)
    print ("{:46} {:.3f} ".format(name, acc.mean()))
    
    #score_opf = cross_val_score(O,features,labels,cv=10)
    #print("{:41} {:.3f} (+/- {:.3f}) ".format(name, score_opf.mean(), score_opf.std() * 2))
    

In [26]:
train_feat,test_feat,train_labels,test_labels = train_test_split(features,labels, test_size=0.20,random_state=42 )

print ("Training set:", train_feat.shape[0], "samples")
print ("Test set:", test_feat.shape[0], "samples")

Training set: 1539 samples
Test set: 385 samples


In [27]:
#def one_hot(labels):
    
#    values = array(labels)

    #print(values)
    #print(len(values))
    
    # integer encode
#    label_encoder = LabelEncoder()
#    integer_encoded1 = label_encoder.fit_transform(values)
    #print("1111111111111", integer_encoded1)
    #print(type(integer_encoded1))
    
    # binary encode
#    onehot_encoder = OneHotEncoder(sparse=False)
#    integer_encoded = integer_encoded1.reshape(len(integer_encoded1), 1)
#    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    #print(onehot_encoded)
    #print(type(onehot_encoded))
#    return onehot_encoded
    #return integer_encoded1

In [28]:
#def invert_oh():
    # invert
#    label_encoder = LabelEncoder()
#    integer_encoded1 = label_encoder.fit_transform(values)
#    onehot_encoder = OneHotEncoder(sparse=False)
#    integer_encoded = integer_encoded1.reshape(len(integer_encoded1), 1)
#    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    
#    inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
#    return inverted
    #print(inverted)

In [29]:
#train_labels_oh = one_hot(train_labels)

In [30]:
#test_labels_oh = one_hot(test_labels)

In [31]:
#print(train_labels)
#print(test_labels)
#print(train_labels_oh)
#print(test_labels_oh)

In [32]:
print(type(test_labels))

<class 'numpy.ndarray'>


In [33]:
C=1
models = (SVC(kernel='linear', C=C, gamma='auto'),
          SVC(kernel='rbf', gamma=0.5, C=C),
          SVC(kernel='poly', degree=3, C=C, gamma='auto'),
          KNeighborsClassifier(3),
          DecisionTreeClassifier(max_depth=8),
          RandomForestClassifier(max_depth=8, n_estimators=10, max_features=1),          
          AdaBoostClassifier(),
          GaussianNB(),
         )

names = ["SVC with linear kernel","SVC with RBF kernel","SVC with polynomial (degree 3) kernel",
         "K Nearest Neighbors","Decision Tree", "Random Forest", "AdaBoost","Naive Bayes"]


k-holdout validation

In [34]:
print ("      Classifiers: \t Accuracy:".expandtabs(44))
for name, clf in zip(names, models):    
    clf.fit(train_feat,train_labels) #train each model
    scores = clf.score(test_feat,test_labels) #evaluate each model in the test set
    print ("{:46} {:.3f} ".format(name, scores.mean()))
opf()

      Classifiers:                           Accuracy:
SVC with linear kernel                         0.769 
SVC with RBF kernel                            0.156 
SVC with polynomial (degree 3) kernel          0.792 
K Nearest Neighbors                            0.540 
Decision Tree                                  0.460 
Random Forest                                  0.460 
AdaBoost                                       0.444 
Naive Bayes                                    0.403 
OPF                                            0.545 


k-fold cross validation

In [35]:
# vou deixar a cross validation inativa por enquanto.

print ("      Classifiers: \t Accuracy (standard deviation)".expandtabs(37))
for name, clf in zip(names, models):    
    scores = cross_val_score(clf,features,labels,cv=10) #train and evaluate each model in each fold    
    print ("{:41} {:.3f} (+/- {:.3f}) ".format(name, scores.mean(), scores.std() * 2))
    
#opf()


      Classifiers:                    Accuracy (standard deviation)
SVC with linear kernel                    0.700 (+/- 0.123) 
SVC with RBF kernel                       0.190 (+/- 0.002) 
SVC with polynomial (degree 3) kernel     0.706 (+/- 0.112) 
K Nearest Neighbors                       0.412 (+/- 0.097) 
Decision Tree                             0.397 (+/- 0.103) 
Random Forest                             0.419 (+/- 0.113) 
AdaBoost                                  0.408 (+/- 0.113) 
Naive Bayes                               0.387 (+/- 0.125) 
